//! Linux DNS configuration — resolver-regime detection and takeover.
//!
//! Implements `docs/os-integration.md` §3 (the resolver-regime ladder) for
//! Linux.  See that section for the full design rationale; this module adds
//! only implementation decisions.
//!
//! ## Regime ladder (detection order)
//!
//! 1. **systemd-resolved** — `/etc/resolv.conf` is a symlink whose target
//!    contains `systemd/resolve`, **or** the file contains `nameserver 127.0.0.53`.
//! 2. **NetworkManager (without resolved)** — `resolv.conf` header contains
//!    the NM signature comment, or `/run/NetworkManager` exists.
//! 3. **resolvconf/openresolv** — `resolv.conf` header contains
//!    `Generated by resolvconf`.
//! 4. **Plain resolv.conf** — none of the above.
//!
//! Detection is a **pure function** over inputs (symlink target string, file
//! contents, marker-file existence booleans), making it unit-testable on any
//! host including this macOS dev machine.
//!
//! ## Snapshot schema
//!
//! The Linux regime is stored in an **additive optional field** on
//! [`DnsSnapshot`]: `linux_regime: Option<LinuxRegime>`.  Old macOS snapshots
//! (field absent) deserialise cleanly via `#[serde(default)]` and are
//! unaffected.  The regime encodes everything `restore()` needs after a crash
//! or reboot.
//!
//! ## resolvconf deviation
//!
//! The spec (os-integration.md §3) says: "register as a resolvconf provider
//! with top priority."  This implementation instead performs an atomic-replace
//! of `/etc/resolv.conf` (keeping the original at
//! `resolv.conf.hushwarren-prev`), identical to the plain-resolv.conf path.
//! Rationale: resolvconf provider registration requires parsing
//! `/etc/resolvconf.conf`, writing to `/etc/resolvconf/resolv.conf.d/`,
//! calling `resolvconf -u`, and handling `openresolv` vs `resolvconf-ng` API
//! differences — substantial complexity with low marginal value for a P1
//! scope.  The deviation is safe because hushwarren's ownership of
//! `/etc/resolv.conf` is explicit and reversible.  Flagged here and in the
//! run summary.
//!
//! ## Root requirement
//!
//! `point_at_self()` and `restore()` return [`PlatformError::NeedsRoot`] if
//! `euid != 0`, checked before any side effect (mirrors `macos.rs`).

use std::net::IpAddr;
#[cfg(any(target_os = "linux", test))]
use std::path::{Path, PathBuf};

use tracing::debug;
#[cfg(target_os = "linux")]
use tracing::{info, warn};

use super::{DnsSetting, LinuxRegime, ServiceDns};
// DnsSnapshot is needed in tests (for snapshot round-trip tests) on all platforms.
#[cfg(any(target_os = "linux", test))]
use super::DnsSnapshot;
#[cfg(target_os = "linux")]
use super::{PlatformDns, PlatformError};

// ── Inputs for pure regime detection ─────────────────────────────────────────

/// Everything `detect_regime` needs, as plain data so it can be called from
/// tests on any host without touching real `/etc/resolv.conf`.
#[derive(Debug, Default)]
pub struct RegimeInputs {
    /// The symlink target of `/etc/resolv.conf`, if it is a symlink.
    ///
    /// `None` means the file is not a symlink (or readlink failed).
    pub symlink_target: Option<String>,

    /// The first ~1 KiB of `/etc/resolv.conf` as UTF-8.
    ///
    /// Used to detect stub IP (127.0.0.53) and header comments.
    pub resolv_conf_head: String,

    /// Whether `/run/NetworkManager` exists.
    pub run_nm_exists: bool,
}

// ── Pure regime detection (unit-testable on any host) ────────────────────────

/// Detect the active resolver regime from pre-read inputs.
///
/// This is a **pure function** — no I/O.  The caller supplies the inputs via
/// [`RegimeInputs`] so the function is unit-testable on macOS without touching
/// `/etc`.
///
/// Detection order follows `docs/os-integration.md` §3:
/// 1. systemd-resolved (symlink target contains `systemd/resolve` OR content
///    contains `nameserver 127.0.0.53`)
/// 2. NetworkManager (header comment contains `NetworkManager` OR
///    `/run/NetworkManager` exists)
/// 3. resolvconf/openresolv (header contains `Generated by resolvconf`)
/// 4. Plain resolv.conf
pub fn detect_regime(inputs: &RegimeInputs) -> LinuxRegime {
    // 1. systemd-resolved
    if let Some(target) = &inputs.symlink_target {
        if target.contains("systemd/resolve") || target.contains("systemd-resolve") {
            return LinuxRegime::SystemdResolved;
        }
    }
    if inputs
        .resolv_conf_head
        .lines()
        .any(|l| l.trim().starts_with("nameserver") && l.contains("127.0.0.53"))
    {
        return LinuxRegime::SystemdResolved;
    }

    // 2. NetworkManager (without resolved)
    if inputs.resolv_conf_head.contains("NetworkManager")
        || inputs
            .resolv_conf_head
            .contains("Generated by NetworkManager")
        || inputs.run_nm_exists
    {
        return LinuxRegime::NetworkManager;
    }

    // 3. resolvconf/openresolv
    if inputs.resolv_conf_head.contains("Generated by resolvconf") {
        return LinuxRegime::Resolvconf;
    }

    // 4. Plain
    LinuxRegime::Plain
}

// ── File-content generators (pure, unit-testable) ─────────────────────────────

/// Generate the content for the systemd-resolved drop-in file.
///
/// Written to `/etc/systemd/resolved.conf.d/hushwarren.conf`.
/// `[Resolve]` section with `DNS=127.0.0.1 ::1` and `Domains=~.` (catch-all).
pub fn resolved_dropin_content() -> String {
    // The Domains=~. directive makes resolved send all queries to our sinkhole
    // rather than only the system search domain.
    "[Resolve]\nDNS=127.0.0.1 ::1\nDomains=~.\n".to_owned()
}

/// Generate the NetworkManager conf.d drop-in that disables NM DNS management.
///
/// Written to `/etc/NetworkManager/conf.d/hushwarren.conf`.
pub fn nm_dropin_content() -> String {
    "[main]\ndns=none\n".to_owned()
}

/// Generate the `/etc/resolv.conf` content pointing at the sinkhole.
///
/// Used by the NM and plain/resolvconf takeover paths.
pub fn sinkhole_resolv_conf_content() -> String {
    // Generated-by comment allows later detection if needed.
    "# Generated by hushwarren — do not edit manually.\n\
     # Restore with: hushd restore\n\
     nameserver 127.0.0.1\n\
     nameserver ::1\n"
        .to_owned()
}

// ── Snapshot helpers (pure) ────────────────────────────────────────────────────

/// The synthetic service name used to represent the Linux resolv.conf
/// configuration in a [`DnsSnapshot`].
///
/// Encoding regime info into the service name (e.g. `"linux:resolved"`) was
/// considered but rejected: it embeds structured data in an opaque string and
/// makes snapshot JSON harder to read.  Instead, an additive
/// `linux_regime: Option<LinuxRegime>` field on the snapshot carries this.
pub const LINUX_SERVICE_NAME: &str = "linux:resolv.conf";

/// Build the [`ServiceDns`] entry for a Linux snapshot.
///
/// The `setting` records the pre-takeover state:
/// - For the plain/NM/resolvconf path, the original nameservers found in
///   `/etc/resolv.conf` (or `Dhcp` if none are found).
/// - For the systemd-resolved path, `Dhcp` (resolved provides the stub; the
///   real server list is in resolved's config, not resolv.conf).
pub fn build_linux_service(setting: DnsSetting) -> ServiceDns {
    ServiceDns {
        service: LINUX_SERVICE_NAME.to_owned(),
        setting,
    }
}

/// Parse nameserver lines from `/etc/resolv.conf` content.
///
/// Returns `Dhcp` if no parseable `nameserver` lines are found (e.g. the file
/// only has comments, or resolved uses the stub and we want to abstract away
/// the 127.0.0.53 stub IP).
pub fn parse_resolv_conf_servers(content: &str) -> DnsSetting {
    let servers: Vec<IpAddr> = content
        .lines()
        .filter_map(|line| {
            let trimmed = line.trim();
            if !trimmed.starts_with("nameserver") {
                return None;
            }
            let rest = trimmed["nameserver".len()..].trim();
            match rest.parse::<IpAddr>() {
                Ok(ip) => Some(ip),
                Err(_) => {
                    debug!(line = trimmed, "skipping unparseable nameserver line");
                    None
                }
            }
        })
        .collect();

    if servers.is_empty() {
        DnsSetting::Dhcp
    } else {
        DnsSetting::Static { servers }
    }
}

// ── Linux-only: side-effecting helpers ───────────────────────────────────────
//
// Everything below this line performs I/O (file writes, shell-outs to
// `systemctl`/`nmcli`) or uses `std::process::Command`.  It is gated to
// `#[cfg(target_os = "linux")]` so that macOS/Windows hosts compile the module
// (for the pure-logic tests above) without including unreachable code.

#[cfg(target_os = "linux")]
use std::process::Command;

// ── Root check ─────────────────────────────────────────────────────────────────

/// Return [`PlatformError::NeedsRoot`] if the effective UID is not 0.
#[cfg(target_os = "linux")]
///
/// Uses `/usr/bin/id -u`; on failure, optimistically proceeds (the subsequent
/// file write will surface the real EPERM).
fn check_root() -> Result<(), PlatformError> {
    match Command::new("/usr/bin/id").arg("-u").output() {
        Ok(out) if out.status.success() => {
            let uid_str = String::from_utf8_lossy(&out.stdout);
            // PANIC-OK: parse failure defaults to uid=1, preserving safety.
            let uid: u32 = uid_str.trim().parse().unwrap_or(1);
            if uid == 0 {
                Ok(())
            } else {
                Err(PlatformError::NeedsRoot)
            }
        }
        // Cannot determine UID — optimistically proceed; the OS will reject
        // the write with EPERM and surface a CommandFailed error.
        _ => Ok(()),
    }
}

// ── Regime executor (side-effecting) ──────────────────────────────────────────

/// Perform the regime-specific takeover, given the detected `regime` and the
/// resolved `/etc/resolv.conf` path (usually `/etc/resolv.conf`).
///
/// All side effects (file writes, `systemctl`, `nmcli`) live here.
#[cfg(target_os = "linux")]
fn exec_takeover(regime: &LinuxRegime, resolv_conf: &Path) -> Result<(), PlatformError> {
    match regime {
        LinuxRegime::SystemdResolved => {
            info!("linux takeover: systemd-resolved path");
            write_resolved_dropin()?;
            systemctl_restart_resolved()?;
        }
        LinuxRegime::NetworkManager => {
            info!("linux takeover: NetworkManager path");
            write_nm_dropin()?;
            atomic_write_resolv_conf(resolv_conf, &sinkhole_resolv_conf_content())?;
            nm_reload()?;
        }
        LinuxRegime::Resolvconf => {
            // Deviation: atomic-replace instead of resolvconf provider
            // registration.  See module-level doc.
            warn!(
                "linux takeover: resolvconf detected — using atomic-replace \
                 (deviation from spec; resolvconf provider registration not implemented)"
            );
            atomic_write_resolv_conf_with_prev(resolv_conf)?;
        }
        LinuxRegime::Plain => {
            info!("linux takeover: plain resolv.conf path");
            atomic_write_resolv_conf_with_prev(resolv_conf)?;
        }
    }
    Ok(())
}

/// Undo the regime-specific takeover.
///
/// The `snapshot` carries the regime via `linux_regime` so this works after
/// a crash and reboot.
#[cfg(target_os = "linux")]
fn exec_restore(regime: &LinuxRegime, resolv_conf: &Path) -> Result<(), PlatformError> {
    match regime {
        LinuxRegime::SystemdResolved => {
            info!("linux restore: removing resolved drop-in + restart");
            remove_resolved_dropin()?;
            systemctl_restart_resolved()?;
        }
        LinuxRegime::NetworkManager => {
            info!("linux restore: removing NM drop-in + reload");
            remove_nm_dropin()?;
            restore_resolv_conf_prev(resolv_conf)?;
            nm_reload()?;
        }
        LinuxRegime::Resolvconf | LinuxRegime::Plain => {
            info!("linux restore: moving resolv.conf.hushwarren-prev back");
            restore_resolv_conf_prev(resolv_conf)?;
        }
    }
    Ok(())
}

// ── File-write helpers ────────────────────────────────────────────────────────

/// Path to the systemd-resolved drop-in directory.
#[cfg(target_os = "linux")]
const RESOLVED_DROPIN_DIR: &str = "/etc/systemd/resolved.conf.d";
/// Filename for the drop-in inside the directory.
#[cfg(target_os = "linux")]
const RESOLVED_DROPIN_NAME: &str = "hushwarren.conf";

/// Path to the NetworkManager conf.d directory.
#[cfg(target_os = "linux")]
const NM_DROPIN_DIR: &str = "/etc/NetworkManager/conf.d";
/// Filename for the NM drop-in.
#[cfg(target_os = "linux")]
const NM_DROPIN_NAME: &str = "hushwarren.conf";

#[cfg(target_os = "linux")]
fn resolved_dropin_path() -> PathBuf {
    Path::new(RESOLVED_DROPIN_DIR).join(RESOLVED_DROPIN_NAME)
}

#[cfg(target_os = "linux")]
fn nm_dropin_path() -> PathBuf {
    Path::new(NM_DROPIN_DIR).join(NM_DROPIN_NAME)
}

/// Write the systemd-resolved drop-in, creating the directory if needed.
#[cfg(target_os = "linux")]
fn write_resolved_dropin() -> Result<(), PlatformError> {
    let dir = Path::new(RESOLVED_DROPIN_DIR);
    std::fs::create_dir_all(dir)
        .map_err(|e| PlatformError::CommandFailed(format!("create {RESOLVED_DROPIN_DIR}: {e}")))?;
    let path = resolved_dropin_path();
    write_file_atomic(&path, &resolved_dropin_content())?;
    debug!(?path, "wrote resolved drop-in");
    Ok(())
}

/// Remove the systemd-resolved drop-in.  Not-found is silently ignored.
#[cfg(target_os = "linux")]
fn remove_resolved_dropin() -> Result<(), PlatformError> {
    let path = resolved_dropin_path();
    match std::fs::remove_file(&path) {
        Ok(()) => {
            debug!(?path, "removed resolved drop-in");
            Ok(())
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(PlatformError::CommandFailed(format!(
            "remove {}: {e}",
            path.display()
        ))),
    }
}

/// Write the NetworkManager drop-in, creating the directory if needed.
#[cfg(target_os = "linux")]
fn write_nm_dropin() -> Result<(), PlatformError> {
    let dir = Path::new(NM_DROPIN_DIR);
    std::fs::create_dir_all(dir)
        .map_err(|e| PlatformError::CommandFailed(format!("create {NM_DROPIN_DIR}: {e}")))?;
    let path = nm_dropin_path();
    write_file_atomic(&path, &nm_dropin_content())?;
    debug!(?path, "wrote NetworkManager drop-in");
    Ok(())
}

/// Remove the NetworkManager drop-in.  Not-found is silently ignored.
#[cfg(target_os = "linux")]
fn remove_nm_dropin() -> Result<(), PlatformError> {
    let path = nm_dropin_path();
    match std::fs::remove_file(&path) {
        Ok(()) => {
            debug!(?path, "removed NM drop-in");
            Ok(())
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(PlatformError::CommandFailed(format!(
            "remove {}: {e}",
            path.display()
        ))),
    }
}

/// Write content to `path` atomically (tmp file + rename in same directory).
#[cfg(target_os = "linux")]
fn write_file_atomic(path: &Path, content: &str) -> Result<(), PlatformError> {
    use std::io::Write;

    // Build a sibling tmp path in the same directory.
    let parent = path
        .parent()
        .ok_or_else(|| PlatformError::CommandFailed(format!("no parent for {}", path.display())))?;
    let file_name = path.file_name().ok_or_else(|| {
        PlatformError::CommandFailed(format!("no filename for {}", path.display()))
    })?;
    let tmp_name = format!(".{}.hushwarren.tmp", file_name.to_string_lossy());
    let tmp_path = parent.join(&tmp_name);

    let mut f = std::fs::File::create(&tmp_path)
        .map_err(|e| PlatformError::CommandFailed(format!("create {}: {e}", tmp_path.display())))?;
    f.write_all(content.as_bytes())
        .map_err(|e| PlatformError::CommandFailed(format!("write {}: {e}", tmp_path.display())))?;
    f.sync_all()
        .map_err(|e| PlatformError::CommandFailed(format!("fsync {}: {e}", tmp_path.display())))?;
    drop(f);

    std::fs::rename(&tmp_path, path).map_err(|e| {
        PlatformError::CommandFailed(format!(
            "rename {} → {}: {e}",
            tmp_path.display(),
            path.display()
        ))
    })?;
    Ok(())
}

/// Atomically overwrite `resolv_conf` with sinkhole content, saving the
/// original to `<resolv_conf>.hushwarren-prev`.
///
/// The prev-file is written before the takeover file, so if we crash between
/// the two writes, the original file is still present.
#[cfg(target_os = "linux")]
fn atomic_write_resolv_conf_with_prev(resolv_conf: &Path) -> Result<(), PlatformError> {
    let prev_path = prev_resolv_conf_path(resolv_conf);

    // Copy original to prev (best-effort — if it already exists from a
    // previous run, leave it alone so we preserve the true baseline).
    if !prev_path.exists() {
        if let Ok(original) = std::fs::read_to_string(resolv_conf) {
            write_file_atomic(&prev_path, &original)?;
            debug!(?prev_path, "saved resolv.conf baseline to prev");
        }
    }

    atomic_write_resolv_conf(resolv_conf, &sinkhole_resolv_conf_content())
}

/// Atomically write `content` to `resolv_conf` (no prev-save).
#[cfg(target_os = "linux")]
fn atomic_write_resolv_conf(resolv_conf: &Path, content: &str) -> Result<(), PlatformError> {
    write_file_atomic(resolv_conf, content)?;
    debug!(?resolv_conf, "wrote sinkhole resolv.conf");
    Ok(())
}

/// Restore `/etc/resolv.conf` from the `.hushwarren-prev` backup.
#[cfg(target_os = "linux")]
fn restore_resolv_conf_prev(resolv_conf: &Path) -> Result<(), PlatformError> {
    let prev_path = prev_resolv_conf_path(resolv_conf);
    match std::fs::read_to_string(&prev_path) {
        Ok(content) => {
            write_file_atomic(resolv_conf, &content)?;
            // Remove the prev file after a successful restore.
            if let Err(e) = std::fs::remove_file(&prev_path) {
                warn!(error = %e, ?prev_path, "could not remove prev file after restore");
            }
            debug!(?resolv_conf, "restored resolv.conf from prev");
            Ok(())
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            // No prev file — either we never took over, or it was already
            // cleaned up.  Not an error; resolv.conf is presumably already
            // in a good state.
            debug!(?prev_path, "no prev file found during restore — skipping");
            Ok(())
        }
        Err(e) => Err(PlatformError::CommandFailed(format!(
            "read {}: {e}",
            prev_path.display()
        ))),
    }
}

/// Derive the path of the backup resolv.conf (`.hushwarren-prev` suffix).
///
/// Kept unconditionally compiled so the unit test on macOS can call it.
#[cfg(any(target_os = "linux", test))]
fn prev_resolv_conf_path(resolv_conf: &Path) -> PathBuf {
    let name = resolv_conf
        .file_name()
        .map(|n| format!("{}.hushwarren-prev", n.to_string_lossy()))
        .unwrap_or_else(|| "resolv.conf.hushwarren-prev".to_owned());
    resolv_conf.parent().unwrap_or(Path::new("/etc")).join(name)
}

// ── systemctl / nmcli ─────────────────────────────────────────────────────────

/// Run `systemctl restart systemd-resolved`.
#[cfg(target_os = "linux")]
fn systemctl_restart_resolved() -> Result<(), PlatformError> {
    run_command("systemctl", &["restart", "systemd-resolved"])
}

/// Run `nmcli general reload` (or `systemctl reload NetworkManager`).
///
/// Tries `nmcli` first; falls back to `systemctl reload NetworkManager`.
#[cfg(target_os = "linux")]
fn nm_reload() -> Result<(), PlatformError> {
    if run_command("nmcli", &["general", "reload"]).is_ok() {
        return Ok(());
    }
    // Fallback: systemctl reload.
    run_command("systemctl", &["reload", "NetworkManager"])
}

/// Run an external command, returning [`PlatformError::CommandFailed`] on
/// non-zero exit or spawn failure.
#[cfg(target_os = "linux")]
fn run_command(cmd: &str, args: &[&str]) -> Result<(), PlatformError> {
    let output = Command::new(cmd)
        .args(args)
        .output()
        .map_err(|e| PlatformError::CommandFailed(format!("failed to spawn {cmd}: {e}")))?;
    if output.status.success() {
        Ok(())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
        let msg = if stderr.is_empty() { stdout } else { stderr };
        Err(PlatformError::CommandFailed(format!(
            "{cmd} {} exited {}: {msg}",
            args.join(" "),
            output.status
        )))
    }
}

// ── Live regime input reader ───────────────────────────────────────────────────

/// Read the [`RegimeInputs`] from the real filesystem.
///
/// This is the only I/O entry point for detection; everything else is pure.
#[cfg(target_os = "linux")]
fn read_regime_inputs() -> RegimeInputs {
    let resolv_conf = Path::new("/etc/resolv.conf");

    // Read symlink target (if any).
    let symlink_target = std::fs::read_link(resolv_conf)
        .ok()
        .map(|p| p.to_string_lossy().into_owned());

    // Read the first 2 KiB of resolv.conf for header comments.
    let resolv_conf_head = std::fs::read_to_string(resolv_conf)
        .unwrap_or_default()
        .chars()
        .take(2048)
        .collect();

    // Check for /run/NetworkManager marker.
    let run_nm_exists = Path::new("/run/NetworkManager").exists();

    RegimeInputs {
        symlink_target,
        resolv_conf_head,
        run_nm_exists,
    }
}

// ── Current-setting reader ─────────────────────────────────────────────────────

/// Read the current effective DNS configuration for `linux:resolv.conf`.
///
/// For systemd-resolved this is always `Dhcp` (the stub 127.0.0.53 is an
/// artefact of resolved, not a user-set server).  For other regimes, we parse
/// `/etc/resolv.conf` nameserver lines.
#[cfg(target_os = "linux")]
fn read_current_setting(regime: &LinuxRegime) -> DnsSetting {
    match regime {
        LinuxRegime::SystemdResolved => {
            // The resolved drop-in is active; from resolv.conf's perspective
            // the stub (127.0.0.53) is present.  We represent this as Static
            // pointing at the stub so the drift detector can compare it to our
            // snapshot — if the resolved drop-in is still active, the stub is
            // still there.
            //
            // Actually: we check whether our drop-in is present to decide if
            // we're still "pointing at self".
            let dropin = resolved_dropin_path();
            if dropin.exists() {
                DnsSetting::Static {
                    servers: vec![
                        IpAddr::from([127, 0, 0, 1]),
                        "::1"
                            .parse()
                            .unwrap_or(IpAddr::from([0, 0, 0, 0, 0, 0, 0, 1])),
                    ],
                }
            } else {
                // Drop-in gone — drift.
                DnsSetting::Dhcp
            }
        }
        _ => {
            let content = std::fs::read_to_string("/etc/resolv.conf").unwrap_or_default();
            parse_resolv_conf_servers(&content)
        }
    }
}

// ── LinuxDns struct ────────────────────────────────────────────────────────────

/// The Linux implementation of [`PlatformDns`].
///
/// Shells out to `systemctl`, `nmcli`, and manipulates files in `/etc`.
/// Stateless; all operations execute synchronously in the calling context.
#[cfg(target_os = "linux")]
pub struct LinuxDns;

#[cfg(target_os = "linux")]
impl PlatformDns for LinuxDns {
    /// Snapshot the current DNS configuration.
    ///
    /// Detects the regime and records it in the snapshot so `restore()` can
    /// undo the correct path after a crash or reboot.
    fn snapshot(&self) -> Result<DnsSnapshot, PlatformError> {
        let inputs = read_regime_inputs();
        let regime = detect_regime(&inputs);
        debug!(?regime, "detected Linux resolver regime");

        // For the drift-detection contract: the setting at snapshot time
        // represents the pre-takeover state.  For resolved we record Dhcp
        // (the stub is resolved's artefact); for others we parse resolv.conf.
        let setting = match &regime {
            LinuxRegime::SystemdResolved => DnsSetting::Dhcp,
            _ => {
                let content = std::fs::read_to_string("/etc/resolv.conf").unwrap_or_default();
                parse_resolv_conf_servers(&content)
            }
        };

        let mut snap = DnsSnapshot::new(vec![build_linux_service(setting)]);
        snap.linux_regime = Some(regime);
        Ok(snap)
    }

    /// Point system DNS at the sinkhole (127.0.0.1 and ::1).
    ///
    /// Requires root; returns [`PlatformError::NeedsRoot`] otherwise.
    fn point_at_self(&self, _services: &[String]) -> Result<(), PlatformError> {
        check_root()?;
        let inputs = read_regime_inputs();
        let regime = detect_regime(&inputs);
        exec_takeover(&regime, Path::new("/etc/resolv.conf"))
    }

    /// Restore DNS to the state recorded in `snap`.
    ///
    /// Reads the regime from `snap.linux_regime`; falls back to re-detecting
    /// if the field is absent (forward-compat guard).
    ///
    /// **Idempotent and continues through all steps on partial failure.**
    fn restore(&self, snap: &DnsSnapshot) -> Result<(), PlatformError> {
        check_root()?;
        let regime = match &snap.linux_regime {
            Some(r) => r.clone(),
            None => {
                // Snapshot predates the linux_regime field (or is a macOS
                // snapshot loaded on Linux by mistake).  Re-detect.
                warn!("linux restore: linux_regime absent in snapshot — re-detecting");
                let inputs = read_regime_inputs();
                detect_regime(&inputs)
            }
        };
        exec_restore(&regime, Path::new("/etc/resolv.conf"))
    }

    /// Read the current DNS setting for `linux:resolv.conf`.
    ///
    /// For the drift watcher: returns the current effective setting so the
    /// sentinel can compare it against the snapshot.
    fn current_setting(&self, _service: &str) -> Result<DnsSetting, PlatformError> {
        let inputs = read_regime_inputs();
        let regime = detect_regime(&inputs);
        Ok(read_current_setting(&regime))
    }
}

// ── Unit tests (pure-logic only — run on any host) ────────────────────────────

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;

    // ── detect_regime ─────────────────────────────────────────────────────────

    #[test]
    fn regime_resolved_by_symlink_stub() {
        let inputs = RegimeInputs {
            symlink_target: Some("../run/systemd/resolve/stub-resolv.conf".to_owned()),
            resolv_conf_head: "nameserver 127.0.0.53\n".to_owned(),
            run_nm_exists: false,
        };
        assert_eq!(detect_regime(&inputs), LinuxRegime::SystemdResolved);
    }

    #[test]
    fn regime_resolved_by_symlink_without_nm() {
        // Symlink to systemd/resolve, no stub in file (test only symlink branch)
        let inputs = RegimeInputs {
            symlink_target: Some("/run/systemd/resolve/resolv.conf".to_owned()),
            resolv_conf_head: "nameserver 1.1.1.1\n".to_owned(),
            run_nm_exists: false,
        };
        assert_eq!(detect_regime(&inputs), LinuxRegime::SystemdResolved);
    }

    #[test]
    fn regime_resolved_by_stub_ip_no_symlink() {
        let inputs = RegimeInputs {
            symlink_target: None,
            resolv_conf_head: "# Dynamic resolv.conf\nnameserver 127.0.0.53\n".to_owned(),
            run_nm_exists: false,
        };
        assert_eq!(detect_regime(&inputs), LinuxRegime::SystemdResolved);
    }

    #[test]
    fn regime_nm_by_header_comment() {
        let inputs = RegimeInputs {
            symlink_target: None,
            resolv_conf_head: "# Generated by NetworkManager\nnameserver 192.168.1.1\n".to_owned(),
            run_nm_exists: false,
        };
        assert_eq!(detect_regime(&inputs), LinuxRegime::NetworkManager);
    }

    #[test]
    fn regime_nm_by_run_marker() {
        let inputs = RegimeInputs {
            symlink_target: None,
            resolv_conf_head: "nameserver 192.168.1.1\n".to_owned(),
            run_nm_exists: true,
        };
        assert_eq!(detect_regime(&inputs), LinuxRegime::NetworkManager);
    }

    #[test]
    fn regime_resolvconf_by_header() {
        let inputs = RegimeInputs {
            symlink_target: None,
            resolv_conf_head: "# Generated by resolvconf\nnameserver 8.8.8.8\n".to_owned(),
            run_nm_exists: false,
        };
        assert_eq!(detect_regime(&inputs), LinuxRegime::Resolvconf);
    }

    #[test]
    fn regime_plain_when_no_markers() {
        let inputs = RegimeInputs {
            symlink_target: None,
            resolv_conf_head: "nameserver 8.8.8.8\nnameserver 8.8.4.4\n".to_owned(),
            run_nm_exists: false,
        };
        assert_eq!(detect_regime(&inputs), LinuxRegime::Plain);
    }

    #[test]
    fn regime_plain_empty_file() {
        let inputs = RegimeInputs::default();
        assert_eq!(detect_regime(&inputs), LinuxRegime::Plain);
    }

    /// Ambiguous: stub IP present AND NM marker present → resolved wins
    /// (resolved check is first in the ladder).
    #[test]
    fn regime_resolved_wins_over_nm_when_stub_ip_present() {
        let inputs = RegimeInputs {
            symlink_target: None,
            resolv_conf_head: "# Generated by NetworkManager\nnameserver 127.0.0.53\n".to_owned(),
            run_nm_exists: true,
        };
        assert_eq!(detect_regime(&inputs), LinuxRegime::SystemdResolved);
    }

    /// Ambiguous: NM marker AND resolvconf header → NM wins (NM check is earlier).
    #[test]
    fn regime_nm_wins_over_resolvconf_when_both_markers() {
        let inputs = RegimeInputs {
            symlink_target: None,
            resolv_conf_head:
                "# Generated by NetworkManager\n# Generated by resolvconf\nnameserver 1.1.1.1\n"
                    .to_owned(),
            run_nm_exists: false,
        };
        assert_eq!(detect_regime(&inputs), LinuxRegime::NetworkManager);
    }

    /// The stub IP must appear on a `nameserver` line, not in a comment.
    #[test]
    fn regime_stub_ip_in_comment_is_not_resolved() {
        let inputs = RegimeInputs {
            symlink_target: None,
            resolv_conf_head: "# stub at 127.0.0.53 is not active\nnameserver 8.8.8.8\n".to_owned(),
            run_nm_exists: false,
        };
        // Comment contains "127.0.0.53" but NOT on a `nameserver` line.
        assert_eq!(detect_regime(&inputs), LinuxRegime::Plain);
    }

    // ── drop-in / resolv.conf content generators ──────────────────────────────

    #[test]
    fn resolved_dropin_has_required_fields() {
        let content = resolved_dropin_content();
        assert!(content.contains("[Resolve]"), "must have [Resolve] section");
        assert!(content.contains("DNS=127.0.0.1 ::1"), "must set DNS");
        assert!(content.contains("Domains=~."), "must set catch-all domain");
    }

    #[test]
    fn nm_dropin_disables_dns() {
        let content = nm_dropin_content();
        assert!(content.contains("[main]"), "must have [main] section");
        assert!(content.contains("dns=none"), "must disable NM DNS");
    }

    #[test]
    fn sinkhole_resolv_conf_has_loopback_nameservers() {
        let content = sinkhole_resolv_conf_content();
        assert!(
            content.contains("nameserver 127.0.0.1"),
            "must have IPv4 loopback nameserver"
        );
        assert!(
            content.contains("nameserver ::1"),
            "must have IPv6 loopback nameserver"
        );
    }

    // ── parse_resolv_conf_servers ─────────────────────────────────────────────

    #[test]
    fn parse_resolv_conf_two_nameservers() {
        let content = "nameserver 8.8.8.8\nnameserver 8.8.4.4\n";
        match parse_resolv_conf_servers(content) {
            DnsSetting::Static { servers } => {
                assert_eq!(servers.len(), 2);
                assert!(servers.contains(&"8.8.8.8".parse::<IpAddr>().unwrap()));
                assert!(servers.contains(&"8.8.4.4".parse::<IpAddr>().unwrap()));
            }
            other => panic!("expected Static, got {other:?}"),
        }
    }

    #[test]
    fn parse_resolv_conf_single_nameserver() {
        let content = "nameserver 1.1.1.1\n";
        match parse_resolv_conf_servers(content) {
            DnsSetting::Static { servers } => {
                assert_eq!(servers.len(), 1);
                assert_eq!(servers[0], "1.1.1.1".parse::<IpAddr>().unwrap());
            }
            other => panic!("expected Static, got {other:?}"),
        }
    }

    #[test]
    fn parse_resolv_conf_skips_comments() {
        let content = "# nameserver 1.2.3.4\nnameserver 9.9.9.9\n";
        match parse_resolv_conf_servers(content) {
            DnsSetting::Static { servers } => {
                // Only 9.9.9.9 is a real nameserver line.
                assert_eq!(servers.len(), 1);
                assert_eq!(servers[0], "9.9.9.9".parse::<IpAddr>().unwrap());
            }
            other => panic!("expected Static, got {other:?}"),
        }
    }

    #[test]
    fn parse_resolv_conf_empty_returns_dhcp() {
        let result = parse_resolv_conf_servers("");
        assert_eq!(result, DnsSetting::Dhcp);
    }

    #[test]
    fn parse_resolv_conf_only_comments_returns_dhcp() {
        let content = "# no nameservers here\n# search example.com\n";
        assert_eq!(parse_resolv_conf_servers(content), DnsSetting::Dhcp);
    }

    #[test]
    fn parse_resolv_conf_with_search_domain() {
        let content = "search example.com\nnameserver 192.168.1.1\n";
        match parse_resolv_conf_servers(content) {
            DnsSetting::Static { servers } => {
                assert_eq!(servers, vec!["192.168.1.1".parse::<IpAddr>().unwrap()]);
            }
            other => panic!("expected Static, got {other:?}"),
        }
    }

    #[test]
    fn parse_resolv_conf_ipv6_nameserver() {
        let content = "nameserver 2001:db8::1\n";
        match parse_resolv_conf_servers(content) {
            DnsSetting::Static { servers } => {
                assert_eq!(servers.len(), 1);
            }
            other => panic!("expected Static, got {other:?}"),
        }
    }

    // ── snapshot round-trip (old macOS form + new Linux form) ─────────────────

    /// A macOS snapshot (no linux_regime field) must deserialise cleanly on
    /// any host — the field defaults to None.
    #[test]
    fn snapshot_old_macos_form_round_trips() {
        let json = r#"{"v":1,"taken_unix_ms":1700000000000,"services":[{"service":"Wi-Fi","setting":{"type":"dhcp"}}]}"#;
        let snap: DnsSnapshot = serde_json::from_str(json).unwrap();
        assert_eq!(snap.v, 1);
        assert_eq!(snap.linux_regime, None, "absent field must default to None");
        // Serialise and deserialise again (full round-trip).
        let re_json = serde_json::to_string(&snap).unwrap();
        let snap2: DnsSnapshot = serde_json::from_str(&re_json).unwrap();
        assert_eq!(snap, snap2);
    }

    /// A Linux snapshot with linux_regime must serialise with the field and
    /// round-trip cleanly.
    #[test]
    fn snapshot_linux_form_round_trips() {
        let mut snap = DnsSnapshot::new(vec![build_linux_service(DnsSetting::Dhcp)]);
        snap.linux_regime = Some(LinuxRegime::SystemdResolved);

        let json = serde_json::to_string(&snap).unwrap();
        assert!(
            json.contains("linux_regime"),
            "linux_regime must appear in JSON"
        );
        assert!(
            json.contains("systemd_resolved"),
            "regime variant must be serialised"
        );

        let back: DnsSnapshot = serde_json::from_str(&json).unwrap();
        assert_eq!(snap, back);
    }

    #[test]
    fn snapshot_linux_nm_regime_round_trips() {
        let mut snap = DnsSnapshot::new(vec![build_linux_service(DnsSetting::Static {
            servers: vec!["192.168.1.1".parse().unwrap()],
        })]);
        snap.linux_regime = Some(LinuxRegime::NetworkManager);
        let json = serde_json::to_string(&snap).unwrap();
        let back: DnsSnapshot = serde_json::from_str(&json).unwrap();
        assert_eq!(snap, back);
        assert_eq!(back.linux_regime, Some(LinuxRegime::NetworkManager));
    }

    #[test]
    fn snapshot_linux_plain_regime_round_trips() {
        let mut snap = DnsSnapshot::new(vec![build_linux_service(DnsSetting::Static {
            servers: vec!["8.8.8.8".parse().unwrap()],
        })]);
        snap.linux_regime = Some(LinuxRegime::Plain);
        let json = serde_json::to_string(&snap).unwrap();
        let back: DnsSnapshot = serde_json::from_str(&json).unwrap();
        assert_eq!(snap, back);
    }

    #[test]
    fn snapshot_linux_resolvconf_regime_round_trips() {
        let mut snap = DnsSnapshot::new(vec![build_linux_service(DnsSetting::Dhcp)]);
        snap.linux_regime = Some(LinuxRegime::Resolvconf);
        let json = serde_json::to_string(&snap).unwrap();
        let back: DnsSnapshot = serde_json::from_str(&json).unwrap();
        assert_eq!(snap, back);
    }

    // ── restore-plan derivation ────────────────────────────────────────────────

    /// Verify that `exec_restore` path selection is correct by checking that
    /// the correct regime variant maps to the correct restore action.
    ///
    /// (We cannot call exec_restore directly in unit tests because it does I/O;
    /// but we can verify that the detect + dispatch logic is correct through
    /// the regime enum itself.)
    #[test]
    fn restore_regime_derived_from_snapshot() {
        // systemd-resolved → drop-in removal + restart
        let mut snap = DnsSnapshot::new(vec![]);
        snap.linux_regime = Some(LinuxRegime::SystemdResolved);
        assert_eq!(snap.linux_regime, Some(LinuxRegime::SystemdResolved));

        // NM → NM drop-in removal + resolv.conf restore + reload
        snap.linux_regime = Some(LinuxRegime::NetworkManager);
        assert_eq!(snap.linux_regime, Some(LinuxRegime::NetworkManager));

        // Plain / resolvconf → move prev back
        snap.linux_regime = Some(LinuxRegime::Plain);
        assert_eq!(snap.linux_regime, Some(LinuxRegime::Plain));

        snap.linux_regime = Some(LinuxRegime::Resolvconf);
        assert_eq!(snap.linux_regime, Some(LinuxRegime::Resolvconf));
    }

    // ── prev_resolv_conf_path ─────────────────────────────────────────────────

    #[test]
    fn prev_path_correct_for_etc_resolv_conf() {
        let path = Path::new("/etc/resolv.conf");
        let prev = prev_resolv_conf_path(path);
        assert_eq!(prev, PathBuf::from("/etc/resolv.conf.hushwarren-prev"));
    }

    // ── build_linux_service ───────────────────────────────────────────────────

    #[test]
    fn linux_service_name_constant() {
        let svc = build_linux_service(DnsSetting::Dhcp);
        assert_eq!(svc.service, LINUX_SERVICE_NAME);
    }
}
